# description of this workflow, can be anything you want
name: Package and Release

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pull requests.
on:
  push:
    tags:
      - '[0-9]+-[0-9]+-[0-9]+-*'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      # we first have to clone the AddOn project, this is a required step
      - name: Clone Project
        uses: actions/checkout@v6
        with:
          # you can specify how much of the commit history you want to fetch,
          # which is useful for controlling the length of the automated changelog
          fetch-depth: 0

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and Release
        uses: BigWigsMods/packager@master

      # the -g arg releases with all classic tags
      # uploading to CurseForge requires the X-Curse-Project-ID field in the toc file, or else no upload
      - name: Package and Release for Vanilla Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic

      - name: Package and Release for Burning Crusade Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc

      - name: Package and Release for Wrath of the Lich King Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath

      - name: Package and Release for Cataclysm Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g cata

      - name: Package and Release for Mists of Pandaria Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g mists